// Mapa de aliases bilingues PT/EN para todos os comandos.
// chave = nome canónico, valores = aliases (também se aceita o canónico).
// Usa-se em handler.js: const cmd = resolve(rawCmd);
const ALIASES = {
  // === Sistema / Util ===
  menu:           ["menu","help","ajuda","start","comandos","commands"],
  menucompleto:   ["menucompleto","allmenu","menutudo","fullmenu"],
  totalcomandos:  ["totalcomandos","totalcmds","totalcommands","contar","count"],
  prefix:         ["prefix","prefixo","p"],
  ping:           ["ping","pong","latency","latencia"],
  status:         ["status","stat","info","botinfo"],
  runtime:        ["runtime","uptime","tempo"],
  speed:          ["speed","velocidade","fast"],
  owner:          ["owner","dono","creator","criador"],
  bot:            ["bot","botinfo2"],

  // Submenus
  menuia:         ["menuia","iamenu"],
  menugp:         ["menugp","menugrupo","menugroup"],
  menujogos:      ["menujogos","gamesmenu","menugames"],
  menuacoes:      ["menuacoes","menuacao","actionsmenu"],
  menubrincadeiras:["menubrincadeiras","funmenu","menufun"],
  menuanti:       ["menuanti","antimenu"],
  menuutil:       ["menuutil","utilmenu","tools","ferramentas"],
  menueco:        ["menueco","menueconomia","ecomenu","economymenu"],
  menuadm:        ["menuadm","menuadmin","adminmenu"],
  menudono:       ["menudono","ownermenu","menuowner"],
  menuvip:        ["menuvip","vipmenu"],
  menupremium:    ["menupremium","premiummenu"],
  menudownload:   ["menudownload","downloadmenu","menudl","dlmenu"],
  menurank:       ["menurank","rankmenu"],

  // === IA ===
  ia:             ["ia","ai","gpt","chat","gemini"],
  traduz:         ["traduz","traduzir","translate","tr"],
  resumo:         ["resumo","resumir","summary","sum"],
  ideia:          ["ideia","idea","ideias"],
  corrigir:       ["corrigir","corrige","fix","correct"],
  explica:        ["explica","explicar","explain"],
  codigo:         ["codigo","code","script"],
  debug:          ["debug","depurar"],
  regex:          ["regex","rgx"],
  sql:            ["sql","query"],
  email:          ["email","mail"],
  carta:          ["carta","letter"],
  poema:          ["poema","poem"],
  historia:       ["historia","story"],
  piada:          ["piada","joke"],
  conselho:       ["conselho","advice","conselhos"],
  rima:           ["rima","rhyme"],
  letra:          ["letra","lyrics2"],
  receita:        ["receita","recipe"],
  dieta:          ["dieta","diet"],
  treino:         ["treino","workout"],
  motivacao:      ["motivacao","motivation","frasemotivacional"],
  frase:          ["frase","quote"],
  horoscopo:      ["horoscopo","horoscope"],
  sonho:          ["sonho","dream"],
  bio:            ["bio","biografia"],
  nick:           ["nick","nickname","apelido"],
  fato:           ["fato","fact"],
  noticia:        ["noticia","news"],
  definir:        ["definir","define","definicao"],
  sinonimo:       ["sinonimo","synonym","sin"],
  antonimo:       ["antonimo","antonym","ant"],
  argumento:      ["argumento","argument"],
  comparar:       ["comparar","compare","vs"],
  curiosidade:    ["curiosidade","curio"],

  // === Grupo / Admin ===
  grupoinfo:      ["grupoinfo","groupinfo","gpinfo"],
  admins:         ["admins","listaradmins","admlist"],
  listar:         ["listar","membros","list","members"],
  tagall:         ["tagall","todos","all","everyone","marcartodos"],
  hidetag:        ["hidetag","ht","invisivel"],
  ban:            ["ban","banir","kick","kickar","expulsar","remove","remover"],
  add:            ["add","adicionar","invite","convidar"],
  promover:       ["promover","promote","admin","tornaradmin"],
  despromover:    ["despromover","demote","desadmin"],
  silenciar:      ["silenciar","mute","calar","fechar","close","fechargrupo","gpf"],
  desmutar:       ["desmutar","unmute","abrirgrupo","abrir","open","gpa"],
  linkgrupo:      ["linkgrupo","grouplink","link"],
  resetlink:      ["resetlink","novolink","newlink"],
  apagar:         ["apagar","delete","del","deletar","d"],
  mudarnome:      ["mudarnome","setname","setsubject","gpname"],
  mudardesc:      ["mudardesc","setdesc","gpdesc"],
  marcar:         ["marcar","mention"],
  banword:        ["banword","palavraproibida"],
  desbanword:     ["desbanword","removerpalavra"],
  limpar:         ["limpar","clear","cls"],

  // === Antis ===
  antilink:       ["antilink","antiurl"],
  antifoto:       ["antifoto","antiimg","antiimage"],
  antivideo:      ["antivideo","antivid"],
  antisticker:    ["antisticker","antifig"],
  antistatus:     ["antistatus","antistory"],
  antipv:         ["antipv","antidm","antiprivate"],
  antifake:       ["antifake","antifk"],
  antipalavrao:   ["antipalavrao","antiprofanity","antiwords"],
  antispam:       ["antispam","antiflood"],
  welcome:        ["welcome","bemvindo","wel"],
  goodbye:        ["goodbye","adeus","bye","tchau"],
  setwelcome:     ["setwelcome","setwel","msgwelcome"],
  setgoodbye:     ["setgoodbye","setbye","msgbye"],

  // === Utilidades ===
  // sticker removido (V7-MD)
  toimg:          ["toimg","toimage","img2"],
  qr:             ["qr","qrcode"],
  calc:           ["calc","calcular","math","calcula"],
  horas:          ["horas","hora","time"],
  data:           ["data","date"],
  clima:          ["clima","weather","tempo2"],
  cep:            ["cep","postal"],
  wiki:           ["wiki","wikipedia"],
  google:         ["google","gg","search"],
  yt:             ["yt","youtube","ytsearch"],
  reverse:        ["reverse","inverter","reverter"],
  emoji:          ["emoji","emojis"],
  encurtar:       ["encurtar","short","shorten"],
  ip:             ["ip","getip"],
  github:         ["github","gh"],
  btc:            ["btc","bitcoin"],
  cotacao:        ["cotacao","money2","currency"],
  binario:        ["binario","binary","bin"],
  morse:          ["morse"],
  base64:         ["base64","b64","encode"],
  debase64:       ["debase64","unbase64","decode"],
  uuid:           ["uuid","guid"],
  random:         ["random","aleatorio"],
  senha:          ["senha","password","gerasenha"],

  // === Economia ===
  saldo:          ["saldo","money","grana","balance","carteira"],
  perfil:         ["perfil","profile","me","eu"],
  top:            ["top","ranking","rank","leaderboard","topsaldo"],
  topxp:          ["topxp","ranknivel","topnivel"],
  toplevel:       ["toplevel","topnivel2"],
  daily:          ["daily","diario","recompensa","bonus"],
  trabalhar:      ["trabalhar","work","job","trampar"],
  crime:          ["crime","roubarbanco"],
  roubar:         ["roubar","steal","rob"],
  loja:           ["loja","shop","store"],
  comprar:        ["comprar","buy"],
  items:          ["items","inventario","inventory","mochila","bag"],
  usar:           ["usar","use"],
  pay:            ["pay","pagar","transferir","transfer"],
  trocar:         ["trocar","trocaxp","exchangexp"],
  banco:          ["banco","bank"],

  // === Jogos ===
  ppt:            ["ppt","jokenpo","rps"],
  dado:           ["dado","dice","rolar"],
  moeda:          ["moeda","coin","caracoroa"],
  sorte:          ["sorte","luck"],
  numero:         ["numero","numbergame"],
  roleta:         ["roleta","roulette"],
  cacaniquel:     ["cacaniquel","slot","slots","caça","caçaniquel"],
  blackjack:      ["blackjack","bj","21"],
  forca:          ["forca","hangman"],
  quiz:           ["quiz","perguntas"],
  trivia:         ["trivia","triv"],
  advinha:        ["advinha","guess"],
  oitobola:       ["8ball","oitobola","bolaoito"],
  duelo:          ["duelo","duel","fight"],
  russa:          ["russa","roletarussa","russianroulette"],
  loteria:        ["loteria","lottery"],
  advinhanum:     ["advinhanum","guessnumber"],
  maiormenor:     ["maiormenor","highlow"],
  parimpar:       ["parimpar","oddeven","par"],
  pokemon:        ["pokemon","poke"],
  gato:           ["gato","cat"],
  cachorro:       ["cachorro","dog"],
  meme:           ["meme","memes"],
  anime:          ["anime","animu"],
  // 🆕 Jogo da Velha (tic tac toe) com tabuleiro
  jdv:            ["jdv","jogodavelha","ttt","tictactoe","velha"],
  jdvbot:         ["jdvbot","ttvsbot","velhabot"],
  jdvjogar:       ["jdvjogar","jogar","play2","mover","move"],
  jdvfim:         ["jdvfim","desistir","quitjdv"],

  // === Ações / Brincadeiras ===
  abraco:         ["abraco","abraço","hug"],
  beijo:          ["beijo","kiss"],
  tapa:           ["tapa","slap"],
  soco:           ["soco","punch"],
  mata:           ["mata","kill"],
  casar:          ["casar","casamento","marry"],
  divorciar:      ["divorciar","divorce"],
  ship:           ["ship","amor"],
  reza:           ["reza","pray"],
  chorar:         ["chorar","cry"],
  rir:            ["rir","laugh"],
  dancar:         ["dancar","dance"],
  dormir:         ["dormir","sleep"],
  amizade:        ["amizade","friendship"],
  odio:           ["odio","hate"],
  iq:             ["iq","qi"],
  gay:            ["gay"],
  burro:          ["burro","stupid","stupidmeter"],
  lindo:          ["lindo","handsome","beautiful"],
  feio:           ["feio","ugly"],
  gostosa:        ["gostosa","gata","hot"],
  fofoqueiro:     ["fofoqueiro","gossip"],
  morder:         ["morder","bite"],
  comer:          ["comer","feed","food","eat"],
  afagar:         ["afagar","pat","headpat"],
  cutucar:        ["cutucar","poke"],
  acenar:         ["acenar","wave","oi"],
  highfive:       ["highfive","mais5","cinco"],
  cuddle:         ["cuddle","aconchego"],
  blush:          ["blush","corar","envergonhar"],
  sorrir:         ["sorrir","smile"],
  matar:          ["matar","mata2"],

  // === V3 novos ===
  diag:           ["diag","diagnostico","diagnostic"],
  logs:           ["logs","historico","log"],
  limparlogs:     ["limparlogs","clearlogs","resetlogs"],
  audio:          ["audio","tts","voz","falar"],
  gif:            ["gif","gifanime"],
  donobiz:        ["donobiz","donoinfo","ownerinfo"],
  setstatus:      ["setstatus","botstatus"],
  setpp:          ["setpp","setfoto","setbotfoto"],
  block:          ["block","bloquear"],
  unblock:        ["unblock","desbloquear"],
  donogp:         ["donogp","donoadd","adddono"],
  shizuko:        ["shizuko","apistatus","apiinfo"],

  // === Download ===
  play:           ["play","music","musica"],
  playvid:        ["playvid","video"],
  ytmp3:          ["ytmp3","mp3"],
  ytmp4:          ["ytmp4","mp4"],
  tiktok:         ["tiktok","tt","tk"],
  ig:             ["ig","insta","instagram"],
  fb:             ["fb","facebook"],
  imgsearch:      ["img","wallpaper","imgsearch","imagem"],
  lyrics:         ["lyrics","letra2"],

  // === VIP ===
  vipinfo:        ["vipinfo","viestat"],
  comprarvip:     ["comprarvip","buyvip"],
  ia2:            ["ia2","aivip","superia"],
  megaia:         ["megaia","ia3","longia"],
  ttsvip:         ["ttsvip","tts2","vozvip"],
  stickervip:     ["stickervip","figvip"],
  fastdaily:      ["fastdaily","dailyvip"],
  vipboost:       ["vipboost","boostvip"],
  vipname:        ["vipname","nickvip"],

  // === Premium ===
  premiuminfo:    ["premiuminfo","prinfo","premstat"],
  comprarpremium: ["comprarpremium","buypremium"],
  megapack:       ["megapack","pack"],
  unlimitia:      ["unlimitia","iainfinita"],
  prioridade:     ["prioridade","priority"],
  premiumstats:   ["premiumstats","prstats"],

  // === Dono ===
  join:           ["join","entrar"],
  sairgrupo:      ["sairgrupo","sair","leavegroup","leave"],
  broadcast:      ["broadcast","bc","divulgar"],
  setbotname:     ["setbotname","setname2","botname"],
  modo:           ["modo","mode"],
  resetdb:        ["resetdb","limpezahd","limpezhd","cleardb","reset"],
  addsaldo:       ["addsaldo","addmoney","givesaldo"],
  remsaldo:       ["remsaldo","tirar","removersaldo"],
  addxp:          ["addxp","givexp"],
  banuser:        ["banuser","banglobal","banglob"],
  desbanuser:     ["desbanuser","unban","desbanglobal"],
  setvip:         ["setvip","addvip"],
  unvip:          ["unvip","removervip"],
  setpremium:     ["setpremium","addpremium"],
  unpremium:      ["unpremium","removerpremium"],
  listgrupos:     ["listgrupos","listargrupos","grupos","groups"],
  reiniciar:      ["reiniciar","restart","reboot"],
  exec:           ["exec","eval","run"],
  addcomando:     ["addcomando","addcmd","novocmd"],
  delcomando:     ["delcomando","delcmd","removercmd"],
};

// Inverte para lookup rápido: { "banir": "ban", "kick": "ban", ... }
const reverseMap = {};
for (const [canon, list] of Object.entries(ALIASES)) {
  for (const a of list) reverseMap[a.toLowerCase()] = canon;
}

function resolve(cmd) {
  if (!cmd) return null;
  return reverseMap[cmd.toLowerCase()] || cmd.toLowerCase();
}

function totalAliases() {
  return Object.values(ALIASES).reduce((s, arr) => s + arr.length, 0);
}

function totalCanonical() {
  return Object.keys(ALIASES).length;
}

module.exports = { ALIASES, resolve, totalAliases, totalCanonical, reverseMap };
