// 30+ opções para piadas, cantadas, memes, quiz etc.
module.exports = {
  piadas: [
    "Por que o livro de matemática se suicidou? Tinha problemas demais.",
    "O que o pato disse pra pata? Vem quá!",
    "O que é um pontinho amarelo no céu? Um airbus aboborinha.",
    "Por que a galinha atravessou a rua? Pra mostrar ao tatu que dá pra fazer sem ser atropelado.",
    "Sabe qual é o cúmulo da paciência? Pescar com vara curta em alto-mar.",
    "Por que o computador foi ao médico? Tinha um vírus.",
    "O que faz um pombo correio? Levar mensagens em pdf.",
    "O que o zero disse pro oito? Belo cinto!",
    "Por que o tomate ficou vermelho? Viu a salada se trocando.",
    "O que faz o pato no Polo Norte? Pinguim.",
    "Tava tão frio que vi um vira-lata vivo enrolado num cobertor de cachorro morto.",
    "Por que a abelha tem cabelo loiro? Pra combinar com a colmeia.",
    "Cadê o sapo? — Pulou. — Cadê o pulo? — Acabou.",
    "Qual é o cúmulo da burrice? Subir num pé de alface pra ver o tomate maduro.",
    "Por que o esqueleto não brigou? Não tinha estômago pra isso.",
    "O que a impressora disse pra outra? Essa folha é sua ou tá imprimindo a minha?",
    "Por que o livro de história tava triste? Tinha muitos problemas do passado.",
    "O médico disse: você tem 7 dias. Eu disse: que ótimo, posso assistir uma série.",
    "Sabe quando dá pra confiar 100% num amigo? Quando ele te empresta a senha do wifi.",
    "Cadê meu sapato? — Tá no pé. — E o pé? — Tá no chão. — Resolvido.",
    "O que o pneu disse pro pavê? Sou pavi-mento, você pavi-comer.",
    "Tipo de gente que diz 'eu nunca minto' — esse mente até sobre não mentir.",
    "Sabe o que dá um cego cheirando uma calcinha de Velcro? Crepe.",
    "Por que o relógio foi expulso? Tava sempre dando voltas.",
    "Cadê o corpo do bombeiro? — Foi salvar uma vida. — E a vida? — Acabou.",
    "Definição de paciência: ensinar matemática à galinha.",
    "Cadê o calor? — No verão. — E o verão? — Tá em janeiro.",
    "Por que o pão tava na fila do banco? Tava esperando torrar.",
    "O que disse o tijolo ao cimento? Sem ti não me sustento.",
    "Médico: senhor está com gripe. Paciente: e a vacina? Médico: tá em férias.",
    "Por que o WhatsApp foi ao psicólogo? Tinha duplas mensagens.",
    "Cadê o controle? — Sumiu. — Sumiu pra onde? — Pro mundo dos controles.",
  ],
  cantadas: [
    "Você tem mapa? Porque me perdi nos teus olhos.",
    "Se beleza desse cadeia tu pegavas perpétua.",
    "Tu deves ser cansada... de correr na minha mente o dia todo.",
    "Tu és Wi-Fi? Porque sinto conexão.",
    "Se eu fosse poeta, escrevia um livro só sobre ti.",
    "Tu és a razão de eu acreditar em amor à primeira vista.",
    "Não sou fotógrafo, mas consigo imaginar nós dois juntos.",
    "Tu és a 8ª maravilha do mundo, as outras 7 desistiram.",
    "Posso te seguir? A minha mãe disse pra eu seguir os meus sonhos.",
    "Tu és google? Porque tens tudo que procuro.",
    "Não sou DJ mas posso mixar contigo a noite toda.",
    "Tu és açúcar? Porque adoçaste o meu dia.",
    "Tens band-aid? Porque me machuquei caindo por ti.",
    "Tu és arquiteto? Porque construíste um castelo no meu peito.",
    "Não sei se és pão de queijo, mas tudo em ti me derrete.",
    "Acabei de perder o meu número, dás-me o teu?",
    "Se sorrir queima caloria, contigo já perdi 5kg.",
    "Tu és bateria? Porque sem ti meu coração desliga.",
    "És o motivo do meu domingo ser feliz.",
    "Consegui ver Deus, porque criou um anjo como tu.",
    "Tu és o sol do meu sistema solar.",
    "Já me imaginei contigo no altar.",
    "Posso te chamar de meu? — Meu mundo, minha vida, minha tudo.",
    "Tu és a tradução perfeita de poema.",
    "Se beleza desse trabalho tu eras CEO.",
    "Não sei o que é amor, mas sei que sinto isso por ti.",
    "Tu és a minha música preferida em loop eterno.",
    "Tens passaporte? Porque vais para a minha vida.",
    "Tu és o tipo de erro que eu queria cometer todos os dias.",
    "Acordei pensando em ti, não pergunta como tive o teu nome no sonho.",
    "Tu és a peça que faltava no meu puzzle.",
    "Se amor é crime, prendo-me no teu coração.",
  ],
  memes: [
    "TÔ RINDO DEMAIS 💀",
    "tá osso 😬",
    "isso aí é flopnaldo do méxico 📉",
    "🗿 sigma face ativada",
    "POV: tu vendo isso 🤡",
    "essa doeu 😩",
    "AAAAAAAAA 🗣️🔥",
    "ratoeira ativada 🐀",
    "pão de queijo 🤌",
    "tô passada 💅",
    "skill issue 🎮",
    "respect 💪",
    "deletado da existência ❌",
    "modo gigachad ativado 🗿",
    "fim de jogo 🎮",
    "PARA O TIRO 📸",
    "meme de ouro 🏆",
    "vibe alta 🔥",
    "foi pro saco 🪣",
    "GG WP 🎯",
    "maluco doente 💉",
    "tá solto demais 🥶",
    "não tem mais jeito 🪦",
    "ativou o brabo 😤",
    "olha o flow 🌊",
    "cancelado 🚫",
    "dx9 ativado 💻",
    "ratuíno detectado 🐭",
    "isso é um crime 🚨",
    "rir ou chorar 🤡",
    "minha mãe disse pra não 😂",
    "kkkkkkkkkkkk 💀",
  ],
  quizzes: [
    { q: "Capital de Moçambique?", a: "maputo" },
    { q: "Quanto é 7 × 8?", a: "56" },
    { q: "Em que ano o homem pisou na Lua?", a: "1969" },
    { q: "Quem pintou a Mona Lisa?", a: "leonardo da vinci" },
    { q: "Maior planeta do sistema solar?", a: "jupiter" },
    { q: "Qual o oceano mais profundo?", a: "pacifico" },
    { q: "Quantos continentes existem?", a: "6" },
    { q: "Animal mais rápido do mundo?", a: "guepardo" },
    { q: "Qual o menor país do mundo?", a: "vaticano" },
    { q: "Inventor do telefone?", a: "graham bell" },
    { q: "Capital do Brasil?", a: "brasilia" },
    { q: "Qual o autor de Dom Casmurro?", a: "machado de assis" },
    { q: "Quantos lados tem um octógono?", a: "8" },
    { q: "Quem escreveu Romeu e Julieta?", a: "shakespeare" },
    { q: "Maior deserto do mundo?", a: "antartida" },
    { q: "Qual o rio mais longo?", a: "nilo" },
    { q: "Velocidade da luz (km/s)?", a: "300000" },
    { q: "Capital de Angola?", a: "luanda" },
    { q: "Capital de Portugal?", a: "lisboa" },
    { q: "H2O é?", a: "agua" },
    { q: "Quem descobriu a gravidade?", a: "newton" },
    { q: "Maior país do mundo?", a: "russia" },
    { q: "Em que ano caiu o muro de Berlim?", a: "1989" },
    { q: "Quantos jogadores num time de futebol?", a: "11" },
    { q: "Quantas cordas tem um violão?", a: "6" },
    { q: "Cor primária que com amarelo dá verde?", a: "azul" },
    { q: "Onde fica o Cristo Redentor?", a: "rio de janeiro" },
    { q: "Quem foi Mandela?", a: "presidente sul africano" },
    { q: "Capital do Japão?", a: "toquio" },
    { q: "Qual é a moeda do Brasil?", a: "real" },
  ],
  bola8: [
    "Sim, com toda certeza ✅","Definitivamente sim 🎯","Sem dúvidas ✨","Pode contar com isso 💯",
    "Provavelmente sim 🤔","Tudo indica que sim 👀","Resposta nebulosa, tenta de novo 🌫️",
    "Pergunta depois 🕒","Não posso prever agora ❓","Concentra-te e pergunta de novo 🧘",
    "Não conta com isso 🚫","A minha resposta é não ❌","As fontes dizem não 📰",
    "Muito improvável 😬","Nem pensar 💀",
  ],
  conselhos: [
    "Bebe água 💧","Dorme cedo 😴","Acredita em ti 🌟","Faz exercício 💪","Aprende algo novo 📚",
    "Sê grato 🙏","Foca no presente 🧘","Sai da zona de conforto 🚀","Cuida dos teus 👪",
    "Lê mais livros 📖","Investe em ti 💎","Não compare a tua vida com outros 🌈",
  ],
  insultos_brincadeira: [
    "tá zoado 🤡","capivara dos sonhos 🐹","tá feio mas é tu 😜","ratoíno mor 🐭","carequinha lindo 👨‍🦲",
    "rei dos memes 👑","piada pronta 🎭","embaçado 🌫️","embromador 🐍","arrombadinho 😂",
  ],
  random_facts: [
    "🐙 Polvos têm 3 corações.",
    "🍯 Mel não estraga.",
    "🦒 Girafa dorme apenas 2h por dia.",
    "🌍 Há mais estrelas que grãos de areia.",
    "🐝 Sem abelhas a humanidade durava 4 anos.",
    "💀 Coração de baleia azul pesa ~600kg.",
    "🪐 1 dia em Vénus dura mais que 1 ano em Vénus.",
    "🐌 Caracol dorme 3 anos seguidos.",
    "🦈 Tubarão existia antes das árvores.",
    "🥚 Avestruz põe o maior ovo (1.4kg).",
  ],
};
