// HEXGUARD V4 — descrições + tutorial de comandos para `.help <cmd>`
module.exports = {
  menu:        { desc: "Mostra o menu completo do bot.",                    use: ".menu" },
  ping:        { desc: "Latência, RAM, uptime e estatísticas.",             use: ".ping" },
  prefix:      { desc: "Mostra o prefixo atual.",                           use: ".prefix" },
  dono:        { desc: "Informações do dono e site oficial.",               use: ".dono" },
  perfil:      { desc: "Mostra a tua foto, saldo, XP, level e items.",      use: ".perfil" },
  saldo:       { desc: "Mostra o teu saldo em $UST.",                       use: ".saldo" },
  daily:       { desc: "Recompensa diária.",                                use: ".daily" },
  trabalhar:   { desc: "Ganha saldo trabalhando (cooldown 1h).",            use: ".trabalhar" },
  pay:         { desc: "Transfere saldo para outro usuário.",               use: ".pay @user 500" },
  loja:        { desc: "Mostra os items à venda.",                          use: ".loja" },
  comprar:     { desc: "Compra um item da loja.",                           use: ".comprar katana" },
  ia:          { desc: "Pergunta à IA HEXGUARD (Gemini).",                  use: ".ia o que é amor?" },
  wendel:      { desc: "Conversa com WENDEL (IA do PV).",                   use: ".wendel oi" },
  play:        { desc: "Baixa música do YouTube em MP3.",                   use: ".play one piece opening" },
  playvid:     { desc: "Baixa vídeo do YouTube em MP4.",                    use: ".playvid naruto amv" },
  tiktok:      { desc: "Baixa vídeo do TikTok sem marca de água.",          use: ".tiktok <url>" },
  pinterest:   { desc: "Pesquisa imagens no Pinterest.",                    use: ".pinterest neon city" },
  img:         { desc: "Pesquisa uma imagem.",                              use: ".img gato fofo" },
  sticker:     { desc: "Cria figurinha de imagem/vídeo.",                   use: ".sticker (responde imagem)" },
  ban:         { desc: "Bani usuário (admin).",                             use: ".ban @user" },
  add:         { desc: "Adiciona número ao grupo.",                         use: ".add 258841234567" },
  promover:    { desc: "Promove a admin.",                                  use: ".promover @user" },
  despromover: { desc: "Tira admin.",                                       use: ".despromover @user" },
  silenciar:   { desc: "Fecha o grupo (só admin fala).",                    use: ".silenciar  ou  .fechar 5min" },
  desmutar:    { desc: "Abre o grupo.",                                     use: ".desmutar" },
  delagenda:   { desc: "Cancela agendamento de fechar/abrir do grupo.",     use: ".delagenda" },
  antilink:    { desc: "Liga/desliga antilink.",                            use: ".antilink on" },
  antipalavrao:{ desc: "Liga/desliga antipalavrão (pega no meio do texto).",use: ".antipalavrao on" },
  antipv:      { desc: "Antipv n1 ignora • n2 avisa • n3 bloqueia.",        use: ".antipv 3" },
  setlimite:   { desc: "Define limite de uma anti.",                        use: ".setlimite link 3" },
  modo:        { desc: "Modo: publico|privado|aluguel|parceria|listanegra.",use: ".modo aluguel" },
  ativarbot:   { desc: "Ativa o bot num grupo (aluguel) por X dias.",       use: ".ativarbot 30" },
  ativargrupo: { desc: "Adiciona grupo à lista premium/parceria.",          use: ".ativargrupo parceria" },
  addautoresponder: { desc: "Cria resposta automática.",                    use: ".addautoresponder oi | Olá meu bem 💖" },
  listautoresp:{ desc: "Lista todos os autoresponders.",                    use: ".listautoresp" },
  ffid:        { desc: "Mostra info de uma conta Free Fire.",               use: ".ffid 1234567890" },
  fflike:      { desc: "Envia 100 likes para um ID FF.",                    use: ".fflike 1234567890" },
  ffpp:        { desc: "Pega foto de perfil FF.",                           use: ".ffpp 1234567890" },
  on:          { desc: "Liga o bot (dono).",                                use: ".on" },
  off:         { desc: "Desliga o bot (dono).",                             use: ".off" },
  restart:     { desc: "Reinicia o bot (dono).",                            use: ".restart" },
  addsaldo:    { desc: "Dono adiciona saldo a alguém.",                     use: ".addsaldo @user 5000" },
  setvip:      { desc: "Define VIP por X dias.",                            use: ".setvip @user 30" },
  setpremium:  { desc: "Define PREMIUM por X dias.",                        use: ".setpremium @user 30" },
  diag:        { desc: "Mostra o último erro registado.",                   use: ".diag" },
  jdv:         { desc: "Inicia jogo da velha contra alguém.",               use: ".jdv @user" },
  jdvbot:      { desc: "Joga velha contra o bot (com nível).",              use: ".jdvbot facil" },
  quiz:        { desc: "Pergunta de quiz aleatória.",                       use: ".quiz" },
  resp:        { desc: "Responde o quiz atual.",                            use: ".resp banana" },
  conselho:    { desc: "Recebe um conselho.",                               use: ".conselho" },
  apostar:     { desc: "Aposta saldo num jogo.",                            use: ".apostar 1000" },
  audio:       { desc: "Converte texto em áudio (voz macho rebotica).",     use: ".audio olá pessoal" },
  logo:        { desc: "Cria um logo bonito com texto.",                    use: ".logo HEXGUARD" },
};
